### ISSUE TITLE
Hidden the website link in readme file

### ISSUE THREAD

**Issue by TrangQuach** [epid8060fall2019/EMILYRAYENS-introduction#1]
Hi Emily,

Nice to meet you through your introduction website. Your major is interesting. You are talent too. 

In your Github introduction folder, I see "This is a website to introduce Emily Rayens You can see the website here: https://epid8060fall2019.github.io/EMILYRAYENS-introduction/."

You can hidden the link by: 
1/open README.MD file in Rstudio. 
2/Write down in README
"# Introducing Emily Rayens
This is a website to introduce Emily Rayens You can see the website [here](your URL)"
3/ update the file on githubs

I have one question about your fun fact. How many years are you on music program?
Thanks.

**Comment by Rayense** [comment]
Thanks for the help in hiding the link! I also updated to include more information on my music program but I got my music degree in flute performance!
